version: "3"

services:
  app:
    build:
      context: ./
      dockerfile: dev.Dockerfile
    image: simulator
    container_name: simulator
    restart: always
    volumes:
      - ./src:/app/src
    ports:
      - 3001:3000
